### ISSUE TITLE
Provide a helper to create wrappers in case of varpositional wrapped

### ISSUE THREAD

**Issue by smarie** [smarie/python-makefun#34]
The following fails because the `a` argument ends up in `kwargs`

```python
def f(a, *args):
    pass

@wraps(f)
def foo(*args, **kwargs):
    return f(*args, **kwargs)  # TypeError: f() got multiple values for argument 'a'

foo('hello', 12)
```

We could wish to provide a parameter in `wraps` (or `new_signature`) so that one can receive the various pieces (maybe in a third argument ?) and do the call easily.

**Comment by elchupanebrej** [comment]
Already fixed?

**Comment by smarie** [comment]
indeed ! thanks @elchupanebrej
