### ISSUE TITLE
Is ist possible to avoid using kwargs in implementation

### ISSUE THREAD

**Issue by piccolbo** [smarie/python-makefun#40]
This may get a little far-fetched, sorry.
Is it possible with this package or in python in general to do something like this?
```
@with_signature("f(a)")
def f()
   return a
```
The idea is to promote reuse and thus consistency of function signatures (attempted in package autosig). I have a collection of functions that form an API. They are all supposed to share the same signature (name excluded, which you seem to include in your definition of signature), and let's say, for the sake of the argument, that they don't share any part of the implementation. With your package, as far as I understand, I can store the common signature as a string, and achieve this with the decorator, but  every occurrence of an argument, say `a`, in each function, needs to be replaced with `kwargs['a']`. I would like to offer this capability with no impact on how the body is written. Right now autosig can only check a signature is compliant with a template, but can't replace the actual writing of it. Thanks

**Comment by smarie** [comment]
You can store the common signature as a string or a `Signature` object, yes.
However there needs to be a way for python to inject the argument in your decorated functions :)

So you should at least put some arguments in your decorated functions: either `*args, **kwargs` or `a`, or `a, **kwargs`, etc.. Note that `makefun` will always pass the arguments in a keyword-way if it is possible. So the names have to exist or a variable-keyword argument has to be present.

Your use case seems related to [this stackoverflow question](https://stackoverflow.com/questions/26746441/how-can-a-decorator-pass-variables-into-a-function-without-changing-its-signatur) ?

**Comment by piccolbo** [comment]
Thanks the SO question is really close to what I want, but the accepted answer there is pretty hacky in the author's own assessment. I did make it work using kwargs, but that's not the  solution I was looking for. The crucial point is your "there needs to be a way for python to inject the argument in your decorated functions". My goal is to abstract that way out so that the user doesn't have to do anything about it, neither code with kwargs nor  copy and paste signatures. Maybe it's one step too ambitious for the language, not just for me.

**Comment by smarie** [comment]
I agree with your analysis. Thanks for the feedback !
